PRGM ::= FUNC_DECL PRGM | \epsilon

FUNC_DECL ::= TYPE ident '(' PARAMS ')' '{' STMT_LIST '}'

PARAMS ::= PARAM_LIST | \epsilon
PARAM_LIST ::= PARAM ',' PARAM_LIST | PARAM
PARAM ::= TYPE ident

STMT_LIST ::= STMT STMT_LIST | \epsilon

STMT ::= 'return' EXPR ';' | TYPE ident '=' EXPR ';' | EXPR ';'

EXPR ::= TERM | TERM '+' EXPR | TERM '-' EXPR 
TERM ::= FACTOR | FACTOR '*' TERM | FACTOR '/' TERM
FACTOR ::= '+' ATOM | '-' ATOM
ATOM ::= NUM_LIT | ident | '(' EXPR ')' | ident '(' ARGS ')'

ARGS ::= ARG_LIST | \epsilon
ARG_LIST ::= EXPR ',' ARG_LIST | EXPR

NUM_LIT ::= intlit | floatlit

TYPE ::= 'int' | 'float' | 'char' | 'short' | 'long' | 'double' | 'void'
